---
title: 'ETC5512: Week 7 Unit Info'
subtitle: 'Case study: Probability of Default and Credit Risk'
format: 
  html:
    toc: true
    css: ../../assets/tutorial.css
    embed-resources: true
  pdf:
    toc: true
editor: visual
---

#### Mon April 20th 26 - Sun April 27th 26

**Seminar:**

We'll be learning about data used to assess credit risk in our next case study. We will also learn about how our code smells and some tips and tricks for wrangling big data.

**Before your tutorial:**

The data for this tutorial will be provided via a Google drive link on the tutorial sheet. It's recommended you download this data before you come to class.

**Tutorial:\
\
**To consolidate the lecture material, you'll be using the same credit risk data set to reproduce some of the plots from the lecture.\
 \
You'll also be downloading and processing a subset of the raw data yourself.

**Workshop:**

I'll be running an extended consultation for you to ask questions about your assignment. Remember to post questions to the discuss forum ahead of time.

**Code Review: \
\
**We've started code review. If you haven't yet please sign up for a time slot to chat with one of the teaching team. Part of this week's lecture will give you some additional insight into this process.\
**\
Assessment:**

Assignment 2 is out and is due end of the week.

**Help:\
**\
Remember the discussion board is always there should you have questions. 
