---
title: 'ETC5512: Instructions for Tutorial 4'
author: "Di Cook"
date: "Week 4 Airline case study"
output: 
  html_document:
    toc: true
---

## `r emo::ji("target")` Objectives

In this tutorial, you will learn 

- how to create, and interact, with a database.
- work with tidyverse wrangling verbs to access database
- add tables to an existing database

## `r emo::ji("wrench")` Preparation  

1. This tutorial will use the data that you extracted about US air traffic from   https://www.transtats.bts.gov in tutorial 2. If you had trouble extracting it then, or discarded it, you will need to get a copy in preparation for this tutorial. 
2. Download the airport information table from https://www.transtats.bts.gov. Click on "Aviation" on the left list, and then "Aviation Support Tables" followed by "Download" at bottom right. This has geographic coordinates for all the airports.
3. Ensure that you have these packages (suites of packages) installed on your computer: `DBI`, `RSQLite`, `tidyverse`, `ggmap`, `ggthemes`, `forcats`, `lubridate`, `lutz`. 
4. Set up a special project for this week with the file structure for the exercises to look like:

```
etc5512-week04
├── README.md
├── analysis
│   └── exercise.Rmd
├── data
│   ├── 994615142_T_ONTIME_REPORTING Jan 2020.csv
│   ├── 402312038_T_MASTER_CORD.csv
└── etc5512-week04.Rproj
```

where `README.md` can contains a a short summary of what is going to be done, and where to look for files, like "analysis contains the code to analyse the data", "data contains two files, on airline traffic and another on airport information".

## `r emo::ji("minidisc")` Exercise 4A

Build an sqlite database from your month of data.

a. Read the data into R. It's possible to do this, because this is a small amount of data.
b. Create an sqlite data base called "flights" from the data
c. Do a simple query, collecting all the records for the first day of the month
d. Be sure to replace `???` with what's useful for you.


## `r emo::ji("abacus")` Exercise 4B

Explore your data! These tasks should be done using the dplyr interface, so that the **tidy wrangling verbs** can be used instead of raw SQL functions. (Note that: code is in the `.Rmd` file, but you need to replace `???` with relevant code pieces for it to work for you.)

a. Find the carrier that had the most flights during the month. Determine which carrier this is?

b. Which airport had the most departing traffic?

c. Compute the smallest, largest and median departure delay for the busiest airport. What would it mean if the median departure delay was negative?

d. Make a side-by-side boxplot of the delays for each carrier, at the busiest airport. 
    i. Think about transforming delay because it has a skewed distribution. (If you use a transformation on the axis, check the number of missings. It may be that a lof ot data is excluded and you need to do the transformation with `mutate`.)
    ii. Sort the carrier axis by the median delay (this is tricky! Hint: use the `forcats` package).
    iii. Make nice labels on the axis
    iv. Write a paragraph on what is learned about the delays by carrier
    
e. How many records, of the busiest airport, have missing values for departure delay?

## `r emo::ji("round_pushpin")` Exercise 4C

Here we are going to add a new table with airport information, and use this to make a map of flights. (Note that: code is in the `.Rmd` file, but you need to replace `???` with relevant code pieces for it to work for you.)

a. Read the airport location data into R, and add a table to your database. 
b. Plot the locations on a map. You should filter the airports to only the latest location. Airports sometimes move `r emo::ji("hand_over_mouth")`. An Open Street Map can be downloaded using the `get_map()` function in the `ggmap` package.
c. Now the fun part, lets take a day's worth of flights, and plot all the flights. You will need to join the day of flights data with the airport locations, using both the origin and destination.
d. Choose the two major carriers for your day of data, and make two separate maps of flights, one for each carrier. Compare and contrast the carrier flight patterns. 
e. ADVANCED: Now we are going to examine change in patterns over the course of a day. You will need to convert departure time into a standard time. Then break it into  one of four categories: midnight-6am, 6am-noon, noon-6pm, 6pm-midnight. Using all the carriers again, make separate maps for each quarter of the day.  Compare the traffic over these four time blocks.
f. ADVANCED: Use the standardised times to follow the path of one plane during the day.


